# Generated by Django 5.2.4 on 2025-08-05 22:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        ('resumes', '0003_alter_resume_certifications_alter_resume_projects_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_type', models.CharField(choices=[('cover_letter', 'Cover Letter'), ('resume_analysis', 'Resume Analysis'), ('job_match', 'Job Match Score')], default='cover_letter', max_length=20)),
                ('prompt_used', models.TextField(help_text='The prompt sent to AI model')),
                ('result_text', models.TextField(help_text='Generated content from AI')),
                ('model_used', models.CharField(default='gpt-4o', max_length=50)),
                ('tokens_used', models.IntegerField(blank=True, null=True)),
                ('processing_time', models.FloatField(blank=True, help_text='Time in seconds', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_description', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.jobdescription')),
                ('resume', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resumes.resume')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'analysis_type'], name='analysis_an_user_id_b6ba09_idx'), models.Index(fields=['created_at'], name='analysis_an_created_e6554a_idx')],
            },
        ),
    ]
