# Generated by Django 5.2.4 on 2025-08-08 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisresult',
            name='model_used',
            field=models.CharField(default='gpt-4o', max_length=100),
        ),
    ]
