# Generated by Django 5.2.4 on 2025-08-05 22:47

import django.db.models.deletion
import django.utils.timezone
import jobs.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobDescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('raw_content', models.TextField(help_text='Original job description content')),
                ('document', models.FileField(blank=True, help_text='Optional: Upload job description document', null=True, upload_to=jobs.models.job_document_upload_path)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('job_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('internship', 'Internship'), ('remote', 'Remote'), ('unknown', 'Unknown')], default='unknown', max_length=50)),
                ('salary_range', models.CharField(blank=True, max_length=100, null=True)),
                ('requirements', models.TextField(blank=True, null=True)),
                ('skills_required', models.TextField(blank=True, null=True)),
                ('experience_level', models.CharField(blank=True, max_length=100, null=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('processing_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_descriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job Description',
                'verbose_name_plural': 'Job Descriptions',
                'ordering': ['-created_at'],
            },
        ),
    ]
