# Generated by Django 5.2.4 on 2025-07-26 09:24

import django.core.validators
import django.db.models.deletion
import resumes.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=resumes.models.resume_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx'])])),
                ('original_filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('docx', 'DOCX'), ('pdf', 'PDF')], max_length=10)),
                ('extracted_text', models.TextField(blank=True, null=True)),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['user', '-uploaded_at'], name='resumes_res_user_id_582ba0_idx')],
            },
        ),
    ]
