# Generated by Django 5.2.4 on 2025-08-02 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_resume_certifications_resume_contact_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='certifications',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='projects',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='work_experience',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
